{"name": "Создание задачи с невалидным именем", "status": "passed", "steps": [{"name": "Отправляем POST запрос с невалидным именем: 123", "status": "passed", "start": 1746535610158, "stop": 1746535610338}, {"name": "Проверяем код ответа и сообщение об ошибке", "status": "passed", "start": 1746535610338, "stop": 1746535610338}], "parameters": [{"name": "wrong_jsons", "value": "{'name': 123}"}], "start": 1746535610158, "stop": 1746535610338, "uuid": "78ba2e91-4961-4113-8297-5b97acef6305", "historyId": "45ddfd62d20de69a7b5f87b77b146c59", "testCaseId": "3699e4ae896f50c0ed7ef13f51f1a951", "fullName": "tests.api.test_tasks.TestTasks#test_create_task_invalid_name", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Egors-MacBook-Air.local"}, {"name": "thread", "value": "21580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}