{"name": "Создание задачи с невалидным именем", "status": "passed", "steps": [{"name": "Отправляем POST запрос с невалидным именем: True", "status": "passed", "start": 1746535610601, "stop": 1746535610772}, {"name": "Проверяем код ответа и сообщение об ошибке", "status": "passed", "start": 1746535610772, "stop": 1746535610772}], "parameters": [{"name": "wrong_jsons", "value": "{'name': True}"}], "start": 1746535610601, "stop": 1746535610772, "uuid": "b6c0b301-ee8d-4e3f-9451-f902a6f4c4ba", "historyId": "a1196d5b1b05ee8f1990917be0996b27", "testCaseId": "3699e4ae896f50c0ed7ef13f51f1a951", "fullName": "tests.api.test_tasks.TestTasks#test_create_task_invalid_name", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Egors-MacBook-Air.local"}, {"name": "thread", "value": "21580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}