{"name": "Создание задачи с невалидным именем", "status": "passed", "steps": [{"name": "Отправляем POST запрос с невалидным именем: None", "status": "passed", "start": 1746535611264, "stop": 1746535611429}, {"name": "Проверяем код ответа и сообщение об ошибке", "status": "passed", "start": 1746535611429, "stop": 1746535611429}], "parameters": [{"name": "wrong_jsons", "value": "{'name': None}"}], "start": 1746535611264, "stop": 1746535611430, "uuid": "a1ff465a-ca5f-4ad6-814e-5489fcbc14bb", "historyId": "d83b3eeac75b1d7ae871ee99ac7d03b6", "testCaseId": "3699e4ae896f50c0ed7ef13f51f1a951", "fullName": "tests.api.test_tasks.TestTasks#test_create_task_invalid_name", "labels": [{"name": "parentSuite", "value": "tests.api"}, {"name": "suite", "value": "test_tasks"}, {"name": "subSuite", "value": "TestTasks"}, {"name": "host", "value": "Egors-MacBook-Air.local"}, {"name": "thread", "value": "21580-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.api.test_tasks"}]}